<a href="https://colab.research.google.com/github/PhebeJ/ML-Assignment/blob/main/PhebeJoshua_ML_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

import urllib.request
import os.path

dataFiles = {
    "car_data.csv" : "https://temp-jrj.s3.ap-south-1.amazonaws.com/ml-assignment/car_data.csv"
}

for file_name in dataFiles.keys():

    fname = file_name

    if os.path.isfile(fname):
        continue

    print("Downloading" , fname , "form", dataFiles[file_name])
    urllib.request.urlretrieve(dataFiles[file_name], fname)

# Develop a program to reduce the dimensions of dataset given in ‘car_data.csv’. 

Apply Principal Component Analysis and output a dataset with five attributes. (Note: PCA steps are to be implemented intead of directly invoking it directely )

In [4]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('car_data.csv')
df.head()

Unnamed: 0         make fuel_type  ... city_mpg highway_mpg  price
0           1  alfa-romero       gas  ...       21          27  13495
1           2  alfa-romero       gas  ...       21          27  16500
2           3  alfa-romero       gas  ...       19          26  16500
3           4         audi       gas  ...       24          30  13950
4           5         audi       gas  ...       18          22  17450

[5 rows x 23 columns]

Select Only Numeric data type, also remove the ID column

In [6]:
df = df.select_dtypes('number')
del df['Unnamed: 0']
df.head()

wheel_base  length  width  ...  compression_ratio  city_mpg  highway_mpg
0        88.6   168.8   64.1  ...                9.0        21           27
1        88.6   168.8   64.1  ...                9.0        21           27
2        94.5   171.2   65.5  ...                9.0        19           26
3        99.8   176.6   66.2  ...               10.0        24           30
4        99.4   176.6   66.4  ...                8.0        18           22

[5 rows x 9 columns]

Compute the mean for each columns

In [7]:
mean = []
for column in df:
    try:
        mean.append(df[column].mean())
    except:
        mean.append(0)

mean

[98.75658536585378,
 174.04926829268305,
 65.90780487804875,
 53.724878048780525,
 2555.5658536585365,
 126.90731707317073,
 10.142536585365855,
 25.21951219512195,
 30.75121951219512]

Subtract mean from each values to make resulting mean to 0

In [8]:
data = df - mean
data

wheel_base     length     width  ...  compression_ratio  city_mpg  highway_mpg
0    -10.156585  -5.249268 -1.807805  ...          -1.142537 -4.219512     -3.75122
1    -10.156585  -5.249268 -1.807805  ...          -1.142537 -4.219512     -3.75122
2     -4.256585  -2.849268 -0.407805  ...          -1.142537 -6.219512     -4.75122
3      1.043415   2.550732  0.292195  ...          -0.142537 -1.219512     -0.75122
4      0.643415   2.550732  0.492195  ...          -2.142537 -7.219512     -8.75122
..          ...        ...       ...  ...                ...       ...          ...
200   10.343415  14.750732  2.992195  ...          -0.642537 -2.219512     -2.75122
201   10.343415  14.750732  2.892195  ...          -1.442537 -6.219512     -5.75122
202   10.343415  14.750732  2.992195  ...          -1.342537 -7.219512     -7.75122
203   10.343415  14.750732  2.992195  ...          12.857463  0.780488     -3.75122
204   10.343415  14.750732  2.992195  ...          -0.642537 -6.219512     -5.75122

[205 rows x 9 columns]

Calculate the covariance matrix

In [9]:
cov = np.cov(data.T)
cov

array([[ 3.62617824e+01,  6.49751887e+01,  1.02716150e+01,
         8.67314419e+00,  2.43429675e+03,  1.42766545e+02,
         5.97456165e+00, -1.85320899e+01, -2.25623242e+01],
       [ 6.49751887e+01,  1.52208688e+02,  2.22610352e+01,
         1.48027879e+01,  5.63833620e+03,  3.51081549e+02,
         7.76293814e+00, -5.41505739e+01, -5.98680751e+01],
       [ 1.02716150e+01,  2.22610352e+01,  4.60189957e+00,
         1.46357939e+00,  9.68445072e+02,  6.56977857e+01,
         1.54336736e+00, -9.01985892e+00, -1.00044213e+01],
       [ 8.67314419e+00,  1.48027879e+01,  1.46357939e+00,
         5.97079962e+00,  3.76053991e+02,  6.83270923e+00,
         2.53528462e+00, -7.77546628e-01, -1.80652559e+00],
       [ 2.43429675e+03,  5.63833620e+03,  9.68445072e+02,
         3.76053991e+02,  2.71107874e+05,  1.84430282e+04,
         3.13040714e+02, -2.58002678e+03, -2.85941736e+03],
       [ 1.42766545e+02,  3.51081549e+02,  6.56977857e+01,
         6.83270923e+00,  1.84430282e+04,  1.734113

Calculate the eigen value and the eigen matrix for the covariance matrix

In [10]:
eigenValues, eigenVectors = np.linalg.eig(cov)
eigenValues, eigenVectors

(array([2.72562814e+05, 4.82373570e+02, 4.53909974e+01, 3.88553515e+01,
        7.13332114e+00, 5.72907881e+00, 2.90511511e+00, 7.89694689e-01,
        1.03960752e+00]),
 array([[-8.95068865e-03,  5.21191063e-02, -3.13564035e-01,
         -3.19945145e-01, -6.13720594e-01, -5.49767560e-01,
         -2.76877404e-01, -1.88651500e-01,  7.32690974e-02],
        [-2.07368576e-02,  7.59080557e-02, -3.37455585e-01,
         -8.12808197e-01,  3.46428104e-01,  2.99557945e-01,
         -4.28738052e-02, -9.55793168e-03, -8.71642219e-02],
        [-3.56278491e-03,  1.16373117e-03, -3.64295805e-02,
         -5.34167761e-02, -7.78950101e-03, -7.86754073e-02,
         -2.39007810e-01,  8.96436802e-01,  3.58930796e-01],
        [-1.37927548e-03,  4.09819979e-02, -1.58194912e-01,
         -1.23781854e-01, -2.18684683e-01, -9.07827479e-02,
          9.23636572e-01,  1.62692078e-01,  1.49443197e-01],
        [-9.97323551e-01,  6.55203833e-02,  4.44635717e-03,
          3.05421867e-02, -5.37009397e-03,  8.

Sort `eigenValues`, `eigenVectors` and `columns` based on `eigenValues`

In [11]:
eigenValues, eigenVectors = zip(*sorted(zip(eigenValues, eigenVectors), reverse=True))
_,columns = zip(*sorted(zip(eigenValues, df.columns.values), reverse=True))

eigenValues, eigenVectors, columns

((272562.81448965694,
  482.37356991236527,
  45.39099744165567,
  38.85535150851589,
  7.133321135125311,
  5.729078809206863,
  2.905115114450222,
  1.0396075242387464,
  0.7896946890759104),
 (array([-0.00895069,  0.05211911, -0.31356403, -0.31994515, -0.61372059,
         -0.54976756, -0.2768774 , -0.1886515 ,  0.0732691 ]),
  array([-0.02073686,  0.07590806, -0.33745558, -0.8128082 ,  0.3464281 ,
          0.29955795, -0.04287381, -0.00955793, -0.08716422]),
  array([-0.00356278,  0.00116373, -0.03642958, -0.05341678, -0.0077895 ,
         -0.07867541, -0.23900781,  0.8964368 ,  0.3589308 ]),
  array([-0.00137928,  0.040982  , -0.15819491, -0.12378185, -0.21868468,
         -0.09078275,  0.92363657,  0.16269208,  0.1494432 ]),
  array([-9.97323551e-01,  6.55203833e-02,  4.44635717e-03,  3.05421867e-02,
         -5.37009397e-03,  8.35797387e-03,  2.64266946e-04, -1.16518589e-03,
         -3.13819035e-04]),
  array([-0.06796255, -0.99207218, -0.06747793, -0.07219238,  0.00670411,
  

Take only 5 components and compute the dot product to get final component.

In [12]:
finalColumns = {}
index = 0
for vector in eigenVectors[0:5]:
    finalColumns[columns[index]] = vector.T.dot(data.T)
    index += 1

The 5 principal components are

In [13]:
pd.DataFrame(finalColumns)

wheel_base      length      width      height  curb_weight
0      5.740450    3.146889  -4.681257   -0.234111     9.699283
1      5.740450    3.146889  -4.681257   -0.234111     9.699283
2   -176.342082  101.772457 -10.967563  -63.421315     2.798243
3    144.045688  -81.392470   1.740486   48.966040     0.171037
4   -168.639587   96.187294 -11.955150  -64.034594    -1.809742
..          ...         ...        ...         ...          ...
200 -251.482433  140.298718  -7.243861  -89.441997   -11.289560
201 -310.225674  174.270013 -12.467133 -112.476598   -11.805513
202 -305.127505  171.183881 -16.338377 -107.675347   -11.337100
203 -420.694529  232.780091 -10.519007 -134.948842   -12.678817
204 -318.456900  178.705533 -12.763246 -114.596410   -11.874668

[205 rows x 5 columns]